version: "3.3"
services:
  mongodb:
        image: tozd/meteor-mongodb:2.6
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./mongo/db:/var/lib/mongodb
          - C:\Users\mbj\Documents\GitHub\qrsbuild\config:/etc/service/mongod
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
        networks:
        - saasdemo
  qrs:
    image: qrsmeteor:1.0.0
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
        - MONGO_URL='mongodb://meteor:${MONGODB_CREATE_PWD}@mongodb/meteor' 
        - PORT=3000 
        - ROOT_URL='http://localhost'
    volumes:
        - C:\Users\mbj\Documents\GitHub\qrsbuild\config:/meteorQRS/config
    # configs:
    #   - my_config
    #   - my_other_config
    ports:
    -  "80:3000"
    links:
        - mongodb
    depends_on:
        - mongodb
    networks:
      - saasdemo
networks:
  saasdemo:
# configs:
  # my_config:
  #   file: ./my_config.txt
  # my_other_config:
  #   external: true