version: "3.3"
services:
    mongodb:
        image: mongo
        container_name: "mongodb"
        networks:
        - integrationLAN
    qrs:
        image: qrsmeteor:1.0.0
        environment:
            - MONGO_URL=mongodb://mongodb:27017/
            - VIRTUAL_HOST=foo.bar.com
            - PORT=3000 
            - ROOT_URL=http://localhost
        volumes:
         - C:\Users\mbj\Documents\GitHub\qrsbuild\config:/meteorQRS/config
        ports:
        -  "80:3000"
        links:
        - mongodb
        depends_on:
        - mongodb
        networks:
        - integrationLAN
networks:
    integrationLAN: