version: "3.3"
services: 
    lb:
        image: dockercloud/haproxy
        links:
        - web
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        ports:
        - 80:80 
    mongodb:
        image: mongo
        container_name: "mongodb"
    qrs:
        image: qhose/qrsmeteor:1.0.0
        environment:
            - MONGO_URL=mongodb://mongodb:27017/
            # - VIRTUAL_HOST=qrs.qlik.com
            - PORT=3000 
            - ROOT_URL=http://localhost
        volumes:
         - C:\Users\mbj\Documents\GitHub\QRSMeteor\config:/meteorQRS/config
        ports:
        -  "3000"
        restart: always
        links:
        - mongodb
        depends_on:
        - mongodb
    web:
        image: qhose/sensewebintegration:1.0.0
        environment:
            # - VIRTUAL_HOST=web.qlik.com
            - MONGO_URL=mongodb://mongodb:27017/
            - PORT=3030 
            - ROOT_URL=http://localhost
        volumes:
         - .\config:/senseWebIntegration/config
        ports:
        -  "3030"
        restart: always
        links:
        - mongodb
        depends_on:
        - mongodb
networks:
    default: