version: "3.3"
services: 
    # nginx:
    #     image: nginx:1.9
    #     ports:
    #     - "80:80"
    #     volumes:
    #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #     restart: always
    #     depends_on:
    #     - web
        # - qrs
    lb:
        image: dockercloud/haproxy
        links:
        - qrs
        - web
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        ports:
        -  "80:80"
        depends_on:
        - qrs
        - web
    mongodb:
        image: mongo
        container_name: "mongodb"
    qrs:
        image: qhose/qrsmeteor:2.0.0
        environment:
            - MONGO_URL=mongodb://mongodb:27017/
            - VIRTUAL_HOST=localqrs
            - PORT=3000 
            - ROOT_URL=http://localqrs
        volumes:
         - C:\Users\Qlikexternal\Documents\GitHub\QRSMeteor\dockerConfigMountFolder:/meteorQRS/config
        ports:
        -  "3000"
        # restart: always
        links:
        - mongodb
        depends_on:
        - mongodb
    web:
        image: qhose/sensewebintegration:1.0.0
        environment:
            - VIRTUAL_HOST=localweb
            - MONGO_URL=mongodb://mongodb:27017/
            - PORT=3030 
            - ROOT_URL=http://localweb
        volumes:
         - C:\Users\Qlikexternal\Documents\GitHub\senseWebIntegration:/senseWebIntegration/config
        ports:
        -  "3030"
        restart: always
        links:
        - mongodb
        depends_on:
        - mongodb
networks:
    default: