version: "3.3"
services:
  mongodb:
        image: tozd/mongodb:3.4
        container_name: "mongodb"
        volumes:
          - .\mongo\log:/var/log/mongod
          - .\mongo\data:/var/lib/mongodb" 
        deploy:
          restart_policy:
            condition: on-failure
        ports:
            - 27017:27017
        networks:
        - saasdemo
  qrs:
    image: qrsmeteor:1.0.0
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
        - MONGO_URL='mongodb://meteor:testpassword@mongodb/meteor' 
        - PORT=3000 
        - ROOT_URL='http://localhost'
    volumes:
        - C:\Users\mbj\Documents\GitHub\qrsbuild\config:/meteorQRS/config
    # configs:
    #   - my_config
    #   - my_other_config
    ports:
    -  "80:3000"
    links:
        - mongodb
    depends_on:
        - mongodb
    networks:
      - saasdemo
networks:
  saasdemo:
# configs:
  # my_config:
  #   file: ./my_config.txt
  # my_other_config:
  #   external: true